[tox]
isolated_build = true
envlist =
    docs
    packaging
    py{310,311}-dj{52}-{sqlite,postgresql,psycopg3,postgis,mysql}
    py{312}-dj{52,60}-{sqlite,postgresql,psycopg3,postgis,mysql}
    py{313}-dj{52,60,main}-{sqlite,psycopg3,postgis3,mysql}
    py{314}-dj{52,60,main}-{sqlite,psycopg3,postgis3,mysql}
    py{315}-dj{52,60,main}-{sqlite,psycopg3,postgis3,mysql}

[testenv]
deps =
    dj52: django~=5.2.0
    dj60: django~=6.0
    djmain: https://github.com/django/django/archive/main.tar.gz
    postgresql: psycopg2-binary
    psycopg3: psycopg[binary]
    postgis: psycopg2-binary
    postgis3: psycopg[binary]
    mysql: mysqlclient
passenv=
    CI
    COVERAGE_ARGS
    COVERAGE_FILE
    DB_BACKEND
    DB_NAME
    DB_USER
    DB_PASSWORD
    DB_HOST
    DB_PORT
    DISPLAY
    DJANGO_SELENIUM_TESTS
    GITHUB_*
setenv =
    PYTHONPATH = {toxinidir}
    PYTHONWARNINGS =\
        error::ResourceWarning,\
        error::DeprecationWarning,\
        error::PendingDeprecationWarning,\
        ignore:The RedirectsPanel is deprecated:DeprecationWarning,\
        # This can be removed when we're fully to 6.0
        ignore:The 'partial'and 'partialdef' template tags are now part of Django core:DeprecationWarning
    DB_NAME = {env:DB_NAME:debug_toolbar}
    DB_USER = {env:DB_USER:debug_toolbar}
    DB_HOST = {env:DB_HOST:localhost}
    DB_PASSWORD =  {env:DB_PASSWORD:debug_toolbar}
    DJANGO_SETTINGS_MODULE = tests.settings
allowlist_externals = make
pip_pre = True
dependency_groups =
    dev
commands = python -b -m coverage run -m django test -v2 {posargs:tests}


[testenv:py{310,311,312,313,314,315}-dj{52,60,main}-{postgresql,psycopg3}]
setenv =
    {[testenv]setenv}
    DB_BACKEND = postgresql
    DB_PORT = {env:DB_PORT:5432}


[testenv:py{310,311,312,313,314,315}-dj{52,60,main}-{postgis,postgis3}]
setenv =
    {[testenv]setenv}
    DB_BACKEND = postgis
    DB_PORT = {env:DB_PORT:5432}


[testenv:py{310,311,312,313,314,315}-dj{52,60,main}-mysql]
setenv =
    {[testenv]setenv}
    DB_BACKEND = mysql
    DB_PORT = {env:DB_PORT:3306}


[testenv:py{310,311,312,313,314,315}-dj{52,60,main}-sqlite]
setenv =
    {[testenv]setenv}
    DB_BACKEND = sqlite3
    DB_NAME = ":memory:"


[testenv:docs]
commands = make -C {toxinidir}/docs {posargs:spelling}
dependency_groups =
    docs

[testenv:packaging]
commands =
    python -m build
    twine check --strict dist/*
deps =
 build
 twine
skip_install = true

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314
    3.15: py315

[gh-actions:env]
DB_BACKEND =
    mysql: mysql
    postgresql: postgresql
    psycopg3: psycopg3
    postgis: postgis
    postgis3: postgis3
    sqlite3: sqlite
